version: '2'
services:
  registry:
    restart: always
    image: registry
    container_name: registry
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./data/registry:/var/lib/registry
