version: '2'
services:
  redis:
    restart: always
    image: redis
    container_name: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    # volumes:
      # - ./data/redis:/data
    # command: --appendonly yes
